on:
  push:
    branches:
      - 'master'

name: Push Containers to DockerHub

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        container:
          - "aws-lambda-r"
          - "aws-lambda-rspatial"
          - "aws-lambda-rgrass"
          - "r-arrow"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: jsinghm
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.container }}
          push: true
          tags: jsinghm/${{ matrix.container }}:latest,jsinghm/${{ matrix.container }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
